// =====================================================
// Final Mock Dataset for PREPTRACK (Expanded Version)
// Covers: branches, leaderboards, materials, notifications,
// progresses, results, users
// =====================================================

// -------------------- BRANCHES --------------------
export const branches = [
  {
    id: 101,
    code: "CSE",
    name: "Computer Science and Engineering",
    created: "2022-08-01",
  },
  {
    id: 102,
    code: "ECE",
    name: "Electronics & Communication Engineering",
    created: "2022-08-01",
  },
  {
    id: 103,
    code: "EEE",
    name: "Electrical & Electronics Engineering",
    created: "2022-08-01",
  },
  {
    id: 104,
    code: "ME",
    name: "Mechanical Engineering",
    created: "2022-08-01",
  },
  { id: 105, code: "CE", name: "Civil Engineering", created: "2022-08-01" },
  {
    id: 106,
    code: "AIML",
    name: "Artificial Intelligence & Machine Learning",
    created: "2023-01-01",
  },
  {
    id: 107,
    code: "IT",
    name: "Information Technology",
    created: "2023-01-10",
  },
];

// -------------------- LEADERBOARDS --------------------
export const leaderboards = {
  topContributors: [
    {
      id: "u101",
      rank: 1,
      name: "Priya Sharma",
      branch: "CSE",
      uploads: 72,
      points: 1620,
      avatar: "https://i.pravatar.cc/120?img=12",
    },
    {
      id: "u102",
      rank: 2,
      name: "Rohan Verma",
      branch: "CSE",
      uploads: 66,
      points: 1505,
      avatar: "https://i.pravatar.cc/120?img=8",
    },
    {
      id: "u103",
      rank: 3,
      name: "Ananya Gupta",
      branch: "ECE",
      uploads: 59,
      points: 1440,
      avatar: "https://i.pravatar.cc/120?img=6",
    },
    {
      id: "u104",
      rank: 4,
      name: "Vikram Rathod",
      branch: "CE",
      uploads: 53,
      points: 1380,
      avatar: "https://i.pravatar.cc/120?img=18",
    },
    {
      id: "u105",
      rank: 5,
      name: "Aisha Khan",
      branch: "ME",
      uploads: 48,
      points: 1325,
      avatar: "https://i.pravatar.cc/120?img=4",
    },
    {
      id: "u106",
      rank: 6,
      name: "Nisha Nair",
      branch: "IT",
      uploads: 44,
      points: 1290,
      avatar: "https://i.pravatar.cc/120?img=26",
    },
    {
      id: "u107",
      rank: 7,
      name: "Arjun Patel",
      branch: "AIML",
      uploads: 40,
      points: 1275,
      avatar: "https://i.pravatar.cc/120?img=33",
    },
    {
      id: "u108",
      rank: 8,
      name: "Krishna Rao",
      branch: "EEE",
      uploads: 38,
      points: 1250,
      avatar: "https://i.pravatar.cc/120?img=19",
    },
    {
      id: "u109",
      rank: 9,
      name: "Meena Iyer",
      branch: "ECE",
      uploads: 35,
      points: 1220,
      avatar: "https://i.pravatar.cc/120?img=16",
    },
    {
      id: "u_you",
      rank: 15,
      name: "You (Riduvarshini R S)",
      branch: "CSE",
      uploads: 28,
      points: 980,
      avatar: "https://i.pravatar.cc/120?img=47",
    },
  ],
};

// -------------------- MATERIALS --------------------
export const materials = [
  {
    id: "m1",
    title: "Data Structures - Unit 3 Notes",
    subject: "Data Structures",
    branch: "CSE",
    uploaderId: "u101",
    uploaderName: "Priya Sharma",
    type: "pdf",
    uploadedAt: "2025-10-05",
    downloads: 480,
    likes: 128,
    description: "Detailed notes on trees, graphs, and traversals.",
    fileUrl: "/files/ds-unit3.pdf",
  },
  {
    id: "m2",
    title: "Algorithms - Complexity Cheat Sheet",
    subject: "Algorithms",
    branch: "CSE",
    uploaderId: "u102",
    uploaderName: "Rohan Verma",
    type: "pdf",
    uploadedAt: "2025-09-21",
    downloads: 320,
    likes: 89,
    description: "All important complexities and Big-O examples.",
    fileUrl: "/files/algorithms.pdf",
  },
  {
    id: "m3",
    title: "DBMS - Normalization Guide",
    subject: "DBMS",
    branch: "CSE",
    uploaderId: "u103",
    uploaderName: "Ananya Gupta",
    type: "pdf",
    uploadedAt: "2025-09-18",
    downloads: 275,
    likes: 64,
    description: "1NF, 2NF, 3NF and BCNF explained with examples.",
    fileUrl: "/files/dbms-normalization.pdf",
  },
  {
    id: "m4",
    title: "Operating Systems - PYQ 2024",
    subject: "OS",
    branch: "CSE",
    uploaderId: "u101",
    uploaderName: "Priya Sharma",
    type: "pyq",
    uploadedAt: "2025-08-12",
    downloads: 390,
    likes: 110,
    description: "Last 5 years of OS question papers with solutions.",
    fileUrl: "/files/os-pyq.pdf",
  },
  {
    id: "m5",
    title: "Thermodynamics - Quick Revision",
    subject: "Thermodynamics",
    branch: "ME",
    uploaderId: "u105",
    uploaderName: "Aisha Khan",
    type: "pdf",
    uploadedAt: "2025-10-02",
    downloads: 140,
    likes: 25,
    description: "All important formulas summarized in one page.",
    fileUrl: "/files/thermo.pdf",
  },
  {
    id: "m6",
    title: "Digital Logic - Practice Questions",
    subject: "Digital Logic",
    branch: "ECE",
    uploaderId: "u109",
    uploaderName: "Meena Iyer",
    type: "pdf",
    uploadedAt: "2025-10-01",
    downloads: 165,
    likes: 35,
    description: "Boolean simplification and K-map practice set.",
    fileUrl: "/files/digital-logic.pdf",
  },
  {
    id: "m7",
    title: "Machine Learning - Lab Manual",
    subject: "ML",
    branch: "AIML",
    uploaderId: "u107",
    uploaderName: "Arjun Patel",
    type: "doc",
    uploadedAt: "2025-09-29",
    downloads: 125,
    likes: 22,
    description: "Complete lab exercises and Jupyter notebook guide.",
    fileUrl: "/files/ml-lab.docx",
  },
  {
    id: "m8",
    title: "Network Security - Summary Notes",
    subject: "Network Security",
    branch: "IT",
    uploaderId: "u106",
    uploaderName: "Nisha Nair",
    type: "pdf",
    uploadedAt: "2025-09-19",
    downloads: 150,
    likes: 31,
    description: "Overview of cryptography, firewalls, and protocols.",
    fileUrl: "/files/network-security.pdf",
  },
];

// -------------------- NOTIFICATIONS --------------------
export const notifications = [
  {
    id: "n1",
    title: "Leaderboard updated!",
    body: "Monthly leaderboard for November is live. You’re ranked #15.",
    type: "system",
    read: false,
    createdAt: "2025-11-12T10:00:00.000Z",
  },
  {
    id: "n2",
    title: "New Material Uploaded",
    body: "Rohan Verma uploaded 'Algorithms - Complexity Cheat Sheet'.",
    type: "material",
    read: false,
    createdAt: "2025-11-10T12:00:00.000Z",
  },
  {
    id: "n3",
    title: "Discussion Reply",
    body: "Ananya Gupta replied to your post on DBMS normalization.",
    type: "discussion",
    read: true,
    createdAt: "2025-11-08T09:00:00.000Z",
  },
  {
    id: "n4",
    title: "System Update",
    body: "PrepTrack servers will be under maintenance on Nov 20.",
    type: "alert",
    read: false,
    createdAt: "2025-11-07T06:00:00.000Z",
  },
  {
    id: "n5",
    title: "Result Published",
    body: "Results for Midterm exams are now live in your dashboard.",
    type: "result",
    read: true,
    createdAt: "2025-11-05T08:30:00.000Z",
  },
];

// -------------------- PROGRESSES --------------------
export const progresses = [
  {
    userId: "u101",
    branch: "CSE",
    notesRead: 120,
    pyqsSolved: 350,
    readinessPercent: 92,
    confidenceBySubject: [
      { subject: "DS", level: 95 },
      { subject: "Algo", level: 90 },
      { subject: "DBMS", level: 87 },
      { subject: "OS", level: 91 },
    ],
  },
  {
    userId: "u102",
    branch: "CSE",
    notesRead: 95,
    pyqsSolved: 280,
    readinessPercent: 84,
    confidenceBySubject: [
      { subject: "DS", level: 80 },
      { subject: "Algo", level: 85 },
      { subject: "DBMS", level: 78 },
      { subject: "CN", level: 82 },
    ],
  },
  {
    userId: "u_you",
    branch: "CSE",
    notesRead: 78,
    pyqsSolved: 250,
    readinessPercent: 82,
    confidenceBySubject: [
      { subject: "DS", level: 85 },
      { subject: "DBMS", level: 70 },
      { subject: "OS", level: 90 },
      { subject: "CN", level: 65 },
    ],
  },
  {
    userId: "u105",
    branch: "ME",
    notesRead: 56,
    pyqsSolved: 120,
    readinessPercent: 72,
    confidenceBySubject: [
      { subject: "Thermo", level: 75 },
      { subject: "Mechanics", level: 70 },
    ],
  },
];

// -------------------- RESULTS --------------------
export const results = {
  overallAverage: "86%",
  bestSubject: { subject: "Data Structures", score: "95%" },
  recentScore: { exam: "Algorithms Midterm", score: "92%" },
  rows: [
    {
      id: "r1",
      userId: "u_you",
      subject: "Data Structures",
      exam: "Final Exam",
      score: "95%",
      date: "2025-05-15",
    },
    {
      id: "r2",
      userId: "u_you",
      subject: "Algorithms",
      exam: "Midterm",
      score: "92%",
      date: "2025-04-10",
    },
    {
      id: "r3",
      userId: "u_you",
      subject: "DBMS",
      exam: "Final Exam",
      score: "88%",
      date: "2025-03-20",
    },
    {
      id: "r4",
      userId: "u_you",
      subject: "Operating Systems",
      exam: "Final",
      score: "85%",
      date: "2024-12-15",
    },
    {
      id: "r5",
      userId: "u101",
      subject: "Data Structures",
      exam: "Final",
      score: "96%",
      date: "2024-05-18",
    },
    {
      id: "r6",
      userId: "u105",
      subject: "Thermodynamics",
      exam: "Class Test",
      score: "76%",
      date: "2025-09-12",
    },
    {
      id: "r7",
      userId: "u103",
      subject: "Digital Logic",
      exam: "Midterm",
      score: "84%",
      date: "2025-04-22",
    },
    {
      id: "r8",
      userId: "u109",
      subject: "Microprocessors",
      exam: "Final",
      score: "88%",
      date: "2025-03-25",
    },
  ],
};

// -------------------- USERS --------------------
export const users = [
  {
    id: "u101",
    studentId: "AM.SC.U4CSE23101",
    name: "Priya Sharma",
    email: "priya.sharma@example.com",
    role: "student",
    branch: "CSE",
    semester: 5,
    avatar: "https://i.pravatar.cc/150?img=12",
    joined: "2022-08-01",
    status: "active",
  },
  {
    id: "u102",
    studentId: "AM.SC.U4CSE23102",
    name: "Rohan Verma",
    email: "rohan.verma@example.com",
    role: "student",
    branch: "CSE",
    semester: 5,
    avatar: "https://i.pravatar.cc/150?img=8",
    joined: "2022-08-01",
    status: "active",
  },
  {
    id: "u103",
    studentId: "AM.EC.U4ECE23103",
    name: "Ananya Gupta",
    email: "ananya.gupta@example.com",
    role: "student",
    branch: "ECE",
    semester: 5,
    avatar: "https://i.pravatar.cc/150?img=6",
    joined: "2022-08-01",
    status: "active",
  },
  {
    id: "u104",
    studentId: "AM.CE.U4CIV23104",
    name: "Vikram Rathod",
    email: "vikram.rathod@example.com",
    role: "student",
    branch: "CE",
    semester: 5,
    avatar: "https://i.pravatar.cc/150?img=18",
    joined: "2022-08-01",
    status: "active",
  },
  {
    id: "u105",
    studentId: "AM.ME.U4MEC23105",
    name: "Aisha Khan",
    email: "aisha.khan@example.com",
    role: "student",
    branch: "ME",
    semester: 5,
    avatar: "https://i.pravatar.cc/150?img=4",
    joined: "2022-08-01",
    status: "active",
  },
  {
    id: "u106",
    studentId: "AM.IT.U4IT23106",
    name: "Nisha Nair",
    email: "nisha.nair@example.com",
    role: "student",
    branch: "IT",
    semester: 5,
    avatar: "https://i.pravatar.cc/150?img=26",
    joined: "2023-01-01",
    status: "active",
  },
  {
    id: "u107",
    studentId: "AM.AI.U4AIML23107",
    name: "Arjun Patel",
    email: "arjun.patel@example.com",
    role: "student",
    branch: "AIML",
    semester: 5,
    avatar: "https://i.pravatar.cc/150?img=33",
    joined: "2023-01-10",
    status: "active",
  },
  {
    id: "u108",
    studentId: "AM.EE.U4EEE23108",
    name: "Krishna Rao",
    email: "krishna.rao@example.com",
    role: "student",
    branch: "EEE",
    semester: 5,
    avatar: "https://i.pravatar.cc/150?img=19",
    joined: "2023-01-10",
    status: "active",
  },
  {
    id: "u109",
    studentId: "AM.EC.U4ECE23109",
    name: "Meena Iyer",
    email: "meena.iyer@example.com",
    role: "student",
    branch: "ECE",
    semester: 5,
    avatar: "https://i.pravatar.cc/150?img=16",
    joined: "2023-01-10",
    status: "active",
  },
  {
    id: "admin1",
    name: "Admin User",
    email: "admin@preptrack.com",
    role: "admin",
    avatar: "https://i.pravatar.cc/150?img=3",
    joined: "2021-01-01",
    status: "active",
  },
  {
    id: "u_you",
    studentId: "AM.SC.U4CSE23140",
    name: "Anusha",
    email: "anusha@amrita.edu",
    role: "student",
    branch: "CSE",
    semester: 5,
    avatar: "https://i.pravatar.cc/150?img=47",
    joined: "2022-08-01",
    status: "active",
  },
];
